# Generated by Django 2.0.7 on 2019-12-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=11, verbose_name='名字')),
                ('image', models.ImageField(upload_to='home/%Y/%m', verbose_name='轮播图')),
                ('is_show', models.BooleanField(verbose_name='是否上线')),
                ('order', models.IntegerField(verbose_name='显示顺序')),
                ('movie_id', models.IntegerField(verbose_name='电影ID')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
