# Generated by Django 2.0.7 on 2019-12-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=16, verbose_name='电影名')),
                ('desc', models.TextField(verbose_name='简介')),
                ('image', models.ImageField(upload_to='movie/%Y/%m', verbose_name='电影图')),
                ('url', models.URLField(verbose_name='电影链接')),
                ('is_vip', models.BooleanField(verbose_name='是否为VIP电影')),
                ('up_num', models.IntegerField(verbose_name='点赞数')),
                ('down_num', models.IntegerField(verbose_name='点踩数')),
                ('com_num', models.IntegerField(verbose_name='评论数')),
                ('fav_num', models.IntegerField(verbose_name='收藏数')),
                ('release_time', models.DateTimeField(verbose_name='上映时间')),
            ],
            options={
                'verbose_name': '电影表',
                'verbose_name_plural': '电影表',
            },
        ),
        migrations.CreateModel(
            name='Per2Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='电影')),
            ],
            options={
                'verbose_name': '电影演员',
                'verbose_name_plural': '电影演员',
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=11, verbose_name='名字')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('star_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '演员表',
                'verbose_name_plural': '演员表',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=11, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Tag2Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='电影')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '电影标签',
                'verbose_name_plural': '电影标签',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='movie',
            field=models.ManyToManyField(through='movie.Tag2Movie', to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='per2movie',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Performer', verbose_name='演员'),
        ),
    ]
