# Generated by Django 2.0.7 on 2019-12-17 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='per2movie',
            name='movie',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='电影'),
        ),
        migrations.AlterField(
            model_name='per2movie',
            name='performer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='movie.Performer', verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='tag2movie',
            name='movie',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='电影'),
        ),
        migrations.AlterField(
            model_name='tag2movie',
            name='tag',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='movie.Tag', verbose_name='标签'),
        ),
    ]
