# Generated by Django 2.0.7 on 2019-12-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='movie_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_movie_type', to='movie.Tag', verbose_name='感兴趣的类型'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(blank=True, default='用户20191216201556', max_length=32, verbose_name='昵称'),
        ),
    ]
