# Generated by Django 2.0.7 on 2019-12-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191219_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Comment', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(blank=True, default='用户20191219152908', max_length=32, verbose_name='昵称'),
        ),
    ]
