# Generated by Django 2.0.7 on 2019-12-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191219_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(blank=True, default='用户20191224204908', max_length=32, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='up_movies',
            field=models.ManyToManyField(through='user.UpOrDown', to='movie.Movie'),
        ),
    ]
