# Generated by Django 2.0.7 on 2019-12-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191224_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(blank=True, default='用户20191224205551', max_length=32, verbose_name='昵称'),
        ),
    ]
