# Generated by Django 2.0.7 on 2019-12-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_lines_movie_name'),
        ('user', '0007_auto_20191224_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=256, verbose_name='评论内容')),
                ('lines', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='movie.Lines', verbose_name='台词')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.LinesComment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '台词评论',
                'verbose_name_plural': '台词评论',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '电影评论', 'verbose_name_plural': '电影评论'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(blank=True, default='用户20191225101615', max_length=32, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='linescomment',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
