# Generated by Django 2.0.7 on 2019-12-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20191225_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='vip_time',
            field=models.CharField(max_length=32, null=True, verbose_name='会员到期时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(blank=True, default='用户20191225212729', max_length=32, verbose_name='昵称'),
        ),
    ]
